name: db test
on: [workflow_dispatch]
jobs:
  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mydb:
        image: mysql:5.7
        env:
          DB_DATABASE: ender.com
          DB_USER: root
          DB_PASSWORD: root
    steps:
          - name: Install sudo package
            run: apt update && apt install sudo
          - name: Set up MySQL
            run: |
              sudo /etc/init.d/mysql start
              mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
