name: db test
on: [workflow_dispatch]
jobs:
  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mydb:
        image: mysql:5.7
        env:
          DB_DATABASE: ender.com
          DB_USER: root
          DB_PASSWORD: root
    steps:
          - name: Set up MySQL
            run: |
               apt-get update
               apt-get install -y mysql-client
               mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
