name: db test
on: [workflow_dispatch]
jobs:
  test-container:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container: ubuntu
    services:
      mydb:
        image: mysql:latest
        ports: 
        - 32574:3306
        env:
          DB_DATABASE: ender.com
          DB_USER: root
          DB_PASSWORD: root
    steps:
          - name: Set up MySQL
            run: |
               apt update && apt install sudo
               apt-get update
               apt-get install -y mysql-client
               sudo service mysql start 
               mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"
               mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
